# Uncomment the next line to define a global platform for your project
 platform :ios, '14.2'

target 'rdw' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for rdw
  pod 'GoogleMLKit/TextRecognition'
  target 'rdwTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rdwUITests' do
    # Pods for testing
  end

end
